name: "test hareply"

on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.21.x
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go-version }}'
      - name: vet
        run: go vet ./...
      - name: test
        run: go test -v -race ./...
